//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prova_Poo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class episodio
    {
        public long Id { get; set; }
        public Nullable<long> Id_Serie { get; set; }
        public string Nome { get; set; }
        public Nullable<int> NumeroEpisodio { get; set; }
        public string Avaliacao { get; set; }
    
        public virtual serie serie { get; set; }
    }
}
